Repository vapor/mysql-kit, pull requests merged in 2018-06, with the labels that each got.

#177 Added helper method to initialize connection from connection string
  Sources/MySQL/Database/MySQLDatabaseConfig.swift
  Tests/MySQLTests/MySQLTests.swift
Labels: enhancement

#179 fix deprecated EOF support for MySQL 5.5 and 5.6
  Sources/MySQL/Connection/MySQLConnection+Query.swift
  Sources/MySQL/Connection/MySQLConnection.swift
  Sources/MySQL/Connection/MySQLConnectionHandler.swift
  Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
  Tests/MySQLTests/MySQLTests.swift
  circle.yml
  docker-compose.yml
Labels: bug

#182 partial EOF fix; real
  Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
  Sources/MySQL/Pipeline/MySQLPacketState.swift
  Sources/MySQL/Utilities/ByteBuffer+MySQL.swift
Labels: bug

#181 Possible fix for `.range`
  Sources/MySQL/Query/MySQLQuery+Select.swift
Labels: bug

#184 add support for adding columns _after_ other columns
  Sources/MySQL/SQL/MySQLAlterTable.swift
  Tests/MySQLTests/MySQLTests.swift
Labels: enhancement

#188 data type improvements
  Sources/MySQL/Codable/MySQLDataDecoder.swift
  Sources/MySQL/Connection/MySQLConnection+Query.swift
  Sources/MySQL/Connection/MySQLConnection+SimpleQuery.swift
  Sources/MySQL/Connection/MySQLConnection.swift
  Sources/MySQL/Connection/MySQLConnectionHandler.swift
  Sources/MySQL/Connection/MySQLData.swift
  Sources/MySQL/Database/OldMySQLRowDecoder.swift
  Sources/MySQL/Database/OldMySQLRowEncoder.swift
  Sources/MySQL/Pipeline/MySQLPacketDecoder.swift
  Sources/MySQL/Pipeline/MySQLPacketEncoder.swift
  Sources/MySQL/Protocol/MySQLBinaryResultsetRow.swift
  Sources/MySQL/Protocol/MySQLColumnDefinition41.swift
  Sources/MySQL/Protocol/MySQLComStmtExecute.swift
  Sources/MySQL/Protocol/MySQLComStmtPrepareOK.swift
  Sources/MySQL/Protocol/MySQLEOFPacket.swift
  Sources/MySQL/Protocol/MySQLErrorPacket.swift
  Sources/MySQL/Protocol/MySQLNullBitmap.swift
  Sources/MySQL/Protocol/MySQLPacket+HandshakeV10.swift
  Sources/MySQL/Protocol/MySQLPacket+OK.swift
  Sources/MySQL/Protocol/MySQLResultSetRow.swift
  Sources/MySQL/SQL/MySQLCollate.swift
  Sources/MySQL/SQL/MySQLDataType.swift
  Sources/MySQL/SQL/MySQLDataTypeStaticRepresentable.swift
  Sources/MySQL/SQL/MySQLFractionalSecondsPrecision.swift
  Sources/MySQL/SQL/MySQLQuery+TypeName.swift
  Sources/MySQL/Utilities/ByteBuffer+MySQL.swift
  Sources/MySQL/Utilities/MySQLError.swift
  Tests/MySQLTests/MySQLTests.swift
Labels: bug, enhancement

#192 add CREATE and DROP index queries
  Sources/MySQL/SQL/MySQLDropIndex.swift
  Sources/MySQL/SQL/MySQLGeneric.swift
  Sources/MySQL/SQL/MySQLQuery.swift
Labels: enhancement

#190 store Decimal using Codable impl
  Sources/MySQL/Connection/MySQLData.swift
  Sources/MySQL/Data/MySQLData+Decimal.swift
  Sources/MySQL/SQL/MySQLDataType.swift
  Sources/MySQL/SQL/MySQLDataTypeStaticRepresentable.swift
  Tests/MySQLTests/MySQLTests.swift
Labels: enhancement
