Repository vapor/mysql-kit, pull requests merged in 2020-02, with the labels that each got.

#256 Correctly decode null columns
  Sources/MySQLKit/MySQLDatabase.swift
  Tests/MySQLKitTests/MySQLKitTests.swift
Labels: bug, semver-patch

#257 Alter table syntax + coder fixes
  Sources/MySQLKit/MySQLDataDecoder.swift
  Sources/MySQLKit/MySQLDataEncoder.swift
  Sources/MySQLKit/MySQLDatabase.swift
Labels: enhancement, semver-minor

#260 Fix sub-second date precision
  .github/workflows/test.yml
  Sources/MySQL/Connection/MySQLData.swift
  Tests/MySQLTests/MySQLTests.swift
Labels: bug, semver-patch

#262 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement
